# Generated by Django 5.0.7 on 2024-08-07 07:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact_model",
            name="msg",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
