# Generated by Django 5.0.7 on 2024-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0003_register_model_rename_email_contact_model_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_model",
            name="Password",
            field=models.CharField(max_length=10000),
        ),
    ]
