# Generated by Django 5.0.7 on 2024-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0005_register_model_phoneno_register_model_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_model",
            name="DOB",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
