# Generated by Django 5.0.7 on 2024-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0006_register_model_dob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=60)),
                (
                    "Description",
                    models.TextField(blank=True, max_length=160, null=True),
                ),
                ("Article", models.TextField(max_length=5000)),
                ("Upload", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
        migrations.CreateModel(
            name="Colleges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=50)),
                ("Country", models.CharField(max_length=50)),
                ("Specialization", models.CharField(max_length=50)),
                ("PhoneNo", models.BigIntegerField()),
                ("Email", models.EmailField(max_length=254)),
                ("Website", models.URLField()),
                ("Address", models.TextField(max_length=3100)),
                ("Image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="laws",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Description", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Universities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=50)),
                ("State", models.CharField(max_length=50)),
                ("PhoneNo", models.BigIntegerField()),
                ("Email", models.EmailField(max_length=254)),
                ("Website", models.URLField()),
                ("Address", models.TextField(max_length=3100)),
                ("Image", models.ImageField(upload_to="")),
            ],
        ),
    ]
