# Generated by Django 5.0.7 on 2024-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0008_rename_articles_article_rename_colleges_college_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="Description",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="Title",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="college",
            name="City",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="college",
            name="Country",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="college",
            name="Name",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="college",
            name="Specialization",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="law",
            name="Description",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="law",
            name="Name",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="universitie",
            name="City",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="universitie",
            name="Name",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="universitie",
            name="State",
            field=models.CharField(max_length=10000),
        ),
    ]
