# Generated by Django 5.0.7 on 2024-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0011_register_model_address_register_model_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="register_model",
            name="ProfileImg",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
