# Generated by Django 5.0.7 on 2024-08-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0012_register_model_profileimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_model",
            name="ProfileImg",
            field=models.ImageField(blank=True, upload_to="profile"),
        ),
    ]
