# Generated by Django 5.0.7 on 2024-08-29 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0014_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "Exam_Name",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("Logo", models.ImageField(blank=True, upload_to="data")),
                (
                    "Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EduApp.course"
                    ),
                ),
            ],
        ),
    ]
