# Generated by Django 5.0.7 on 2024-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0015_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="Link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
