# Generated by Django 5.0.7 on 2024-09-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0016_exam_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="statistics",
            fields=[
                (
                    "Stat",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sat_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("Year", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="")),
                (
                    "Stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EduApp.statistics",
                    ),
                ),
            ],
        ),
    ]
