# Generated by Django 5.0.7 on 2024-09-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0017_statistics_sat_detail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="statistics",
            new_name="statistic",
        ),
        migrations.RenameModel(
            old_name="sat_detail",
            new_name="statistic_detail",
        ),
    ]
