# Generated by Django 5.0.7 on 2024-09-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0020_remove_statistic_detail_statistic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="States",
            fields=[
                ("State_Image", models.ImageField(upload_to="")),
                (
                    "State",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="statistic_detail",
            name="State",
        ),
        migrations.RemoveField(
            model_name="statistic_detail",
            name="State_Image",
        ),
        migrations.AddField(
            model_name="statistic_detail",
            name="Statistic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="EduApp.statistic",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statistic_detail",
            name="Title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statistic_detail",
            name="Year",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statistic_detail",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="statistic_detail",
            name="pdf",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
