# Generated by Django 5.0.7 on 2024-09-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0021_states_remove_statistic_detail_state_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="States",
        ),
    ]
