# Generated by Django 5.0.7 on 2024-09-10 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0023_state_and_uni"),
    ]

    operations = [
        migrations.CreateModel(
            name="State_Uni_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Link", models.URLField(blank=True, null=True)),
                (
                    "State_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EduApp.state_and_uni",
                    ),
                ),
            ],
        ),
    ]
