# Generated by Django 5.0.7 on 2024-09-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0024_state_uni_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="state_uni_detail",
            name="State_name",
            field=models.CharField(max_length=1000),
        ),
    ]
