# Generated by Django 5.0.7 on 2024-09-10 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0025_state_uni_detail_state_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="state_uni_detail",
            old_name="State_name",
            new_name="uni_name",
        ),
        migrations.AddField(
            model_name="state_uni_detail",
            name="state_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="EduApp.state_and_uni",
            ),
            preserve_default=False,
        ),
    ]
