# Generated by Django 5.0.7 on 2024-09-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0026_rename_state_name_state_uni_detail_uni_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="State_Uni_detail",
        ),
    ]
