# Generated by Django 5.0.7 on 2024-09-10 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0027_delete_state_uni_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Universitie_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Universities_Name", models.CharField(max_length=1000)),
                ("Link", models.URLField(blank=True, null=True)),
                (
                    "State_Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EduApp.state_and_uni",
                    ),
                ),
            ],
        ),
    ]
