# Generated by Django 5.0.7 on 2024-09-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0028_universitie_details"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Universitie_details",
            new_name="Universities_detail",
        ),
    ]
