# Generated by Django 5.0.7 on 2024-09-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0029_rename_universitie_details_universities_detail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="State_and_Uni",
            new_name="State_and_Universitie",
        ),
    ]
