# Generated by Django 5.0.7 on 2024-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0030_rename_state_and_uni_state_and_universitie"),
    ]

    operations = [
        migrations.CreateModel(
            name="EduInst",
            fields=[
                (
                    "Name",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("Image", models.ImageField(blank=True, upload_to="data")),
                ("Description", models.TextField(max_length=10000)),
            ],
        ),
    ]
