# Generated by Django 5.0.7 on 2024-11-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0032_eduinst_id_alter_eduinst_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eduinst",
            name="id",
        ),
        migrations.AlterField(
            model_name="eduinst",
            name="Name",
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Institutional_Detail",
            fields=[
                (
                    "Inst_Name",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("Image", models.ImageField(blank=True, upload_to="data")),
                ("Description", models.TextField(max_length=10000)),
                (
                    "Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EduApp.course"
                    ),
                ),
            ],
        ),
    ]
