# Generated by Django 5.0.7 on 2024-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0033_remove_eduinst_id_alter_eduinst_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eduinst",
            name="Address",
            field=models.TextField(default=1, max_length=3100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eduinst",
            name="Email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eduinst",
            name="PhoneNo",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="eduinst",
            name="Title",
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eduinst",
            name="Website",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Institutional_Detail",
        ),
    ]
