# Generated by Django 5.0.7 on 2024-11-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0035_rename_title_eduinst_titles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eduinst",
            old_name="Titles",
            new_name="Title",
        ),
    ]
