# Generated by Django 5.0.7 on 2024-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0036_rename_titles_eduinst_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eduinst",
            name="Address",
            field=models.TextField(blank=True, max_length=3100, null=True),
        ),
        migrations.AlterField(
            model_name="eduinst",
            name="Description",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="eduinst",
            name="Email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="eduinst",
            name="Title",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="eduinst",
            name="Website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
