# Generated by Django 5.0.7 on 2024-11-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EduApp",
            "0038_eduinst_completed_courses_eduinst_exam_registrations_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eduinst",
            name="Logo",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
        migrations.AlterField(
            model_name="eduinst",
            name="Link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
