# Generated by Django 5.0.7 on 2024-11-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0039_eduinst_logo_alter_eduinst_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eduinst",
            name="Link",
        ),
    ]
