# Generated by Django 5.0.7 on 2024-11-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0042_eduinst_description1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eduinst",
            name="Description",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
