# Generated by Django 5.0.7 on 2024-11-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0043_alter_eduinst_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
