# Generated by Django 5.0.7 on 2024-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EduApp", "0045_rename_submit_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpandSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=10000)),
                ("Message", models.TextField()),
            ],
        ),
    ]
